In [1]:
import os
import numpy as np
import easyvvuq as uq
import chaospy as cp
import matplotlib.pyplot as plt
from easyvvuq.actions import CreateRunDirectory, Encode, Decode, ExecuteLocal, Actions
from util import persist

# EasyVVUQ on many Benchmarks

## Setting up an EasyVVUQ campaign

In [2]:
# Quantity of Interest
QOI = 'energy_uj'

# location where the run directories are stored
WORK_DIR = '.results'

We first set up the `params` dictionary, in which we specify the name, type and default value of each input
Also the `vary` dictionary, which holds the `chaospy` distribution of each input

In [3]:
params = {}
vary = {}

# Current machine maximum number of cores
params['N_THREADS'] = {'type': 'integer', 'default': 16}
vary['N_THREADS'] = cp.DiscreteUniform(1, 16)

# Levels of Clock speed, for our current machine:
# 2200000 = 0,
# 2800000 = 1,
# 3300000 = 2
params['CLK'] = {'type': 'integer', 'default': 2}
vary['CLK'] = cp.DiscreteUniform(0, 2)

# params['POWER_CAP'] = {'type': 'integer', 'default': 220.0}  # power cap in watts

d = len(params)

In [4]:
# input file encoder
encoder = uq.encoders.GenericEncoder(template_fname='energy.template', delimiter='$', target_filename='input.csv')

The wrapper writes a CSV file `output.csv` containing the energy, in microjoules, used during the programs execution.

In [5]:
# CSV output file decoder
decoder = uq.decoders.SimpleCSV(target_filename='output.csv', output_columns=[QOI])

In [6]:
# Local execution of the wrapper around benchmarks
execute = ExecuteLocal(f'{os.getcwd()}/energy_wrapper.py')

Now we are combine all actions we want to execute into an `Actions` object.

In [7]:
# actions to be undertaken: make rundirs, encode input files, execute local model ensemble, decode output files
actions = Actions(
    CreateRunDirectory(root=WORK_DIR, flatten=True),
    Encode(encoder),
    execute,
    Decode(decoder)
)

The central object in the UQ analysis is a so-called Campaign. This is created as:

In [8]:
campaign = uq.Campaign(name='energy', params=params, actions=actions, work_dir=WORK_DIR)

/home/mmachado/HPC/energyuq/.venv/lib/python3.9/site-packages/cerberus/validator.py:618: UserWarning: These types are defined both with a method and in the'types_mapping' property of this validator: {'integer'}
  warn(


We now select the adaptive Stochastic Collocation sampler. Here

* `polynomial_order = 1`: should be interpreted in the sparse context as starting the sampling plan with a level 1 quadrature rule for all inputs.
* `quadrature_rule='C'`: selects the Clenshaw Curtis quadrature rule.
* `sparse=True`: selects the sparse grid.
* `growth=True`: selects an exponential growth rule which makes the Clenshaw Curtis rule nested.
* `dimension_adaptive=True`: selects the dimension-adaptive sampler.

In [9]:
sampler = uq.sampling.SCSampler(vary=vary, polynomial_order=1, quadrature_rule='C', sparse=True, midpoint_level1=True, dimension_adaptive=True)
campaign.set_sampler(sampler)

## Run campaign and adaptation

Run the first ensemble, which consists of just a single sample:

In [10]:
campaign.execute(sequential=True).collate(progress_bar=True)

Running on Glados
Governor set: Done
Frequency set: Done
energy_uj: Stdout: 6171660769

Running NONE with 8 threads

energy_uj: Stdout: 6172183798
NONE
    Stdout
        Running NONE with 8 threads
        OMP_NUM_THREADS=8
        OMP_PROC_BIND=CLOSE
        OMP_PLACES=CORES
        "Running None"


100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 322.69it/s]


To analyse the results (and execute the dimension adaptivity), we need an `SCAnalysis` object:

In [11]:
analysis = uq.analysis.SCAnalysis(sampler=sampler, qoi_cols=[QOI])

In [12]:
# perform analysis (basically estimates moments, Sobol analysis, and updates internal state of analysis)
campaign.apply_analysis(analysis)

Now we'll refine the grid several times in an anisotropic fashion. Here

* `look_ahead`: determines the new admissible candidate refinements.
* `campaign.get_collation_result()`: get the data frame with all code samples.
* `adapt_dimension`: compute the hierarchical surplus at all candidate refinements, and accept the one with the highest surplus.

In [13]:
def plot_new_points(new_points):
      plt.figure()
      xs = np.array([x for x, y in new_points])
      ys = np.array([y for x, y in new_points])
      plt.plot(xs, ys, 'o')
      plt.show()

def refine_sampling_plan(number_of_refinements):
      """
      Refine the sampling plan.

      Parameters
      ----------
      number_of_refinements (int)
      The number of refinement iterations that must be performed.

      Returns
      -------
      None. The new accepted indices are stored in analysis.l_norm and the admissible indices
      in sampler.admissible_idx.
      """
      for i in range(number_of_refinements):
      # compute the admissible indices
            sampler.look_ahead(analysis.l_norm)

            if sampler.n_new_points[-1] == 0:
                  # maybe we should stop??
                  pass

            if len(sampler.admissible_idx) == 0:
                  # we searched everything
                  break
            
            print(f"-----------------------{i + 1}------------------------")
            print(f"-----------------------{sampler.n_new_points[-1]} new points------------------------")
            # run the ensemble
            campaign.execute(sequential=True).collate(progress_bar=True)

            # accept one of the multi indices of the new admissible set
            data_frame = campaign.get_collation_result()
            analysis.adapt_dimension(QOI, data_frame, method='var')


In [14]:
refine_sampling_plan(50)

-----------------------1------------------------
-----------------------4 new points------------------------
Running on Glados
Governor set: Done
Frequency set: Done
energy_uj: Stdout: 6188269468

Running NONE with 8 threads

energy_uj: Stdout: 6189236169
NONE
    Stdout
        Running NONE with 8 threads
        OMP_NUM_THREADS=8
        OMP_PROC_BIND=CLOSE
        OMP_PLACES=CORES
        "Running None"
Running on Glados
Governor set: Done
Frequency set: Done
energy_uj: Stdout: 6208042707

Running NONE with 12 threads

energy_uj: Stdout: 6208565324
NONE
    Stdout
        Running NONE with 12 threads
        OMP_NUM_THREADS=12
        OMP_PROC_BIND=CLOSE
        OMP_PLACES=CORES
        "Running None"
Running on Glados
Governor set: Done
Frequency set: Done
energy_uj: Stdout: 6219162249

Running NONE with 5 threads

energy_uj: Stdout: 6219667808
NONE
    Stdout
        Running NONE with 5 threads
        OMP_NUM_THREADS=5
        OMP_PROC_BIND=CLOSE
        OMP_PLACES=CORES
        

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 734.20it/s]


[[1 2]]
-----------------------2------------------------
-----------------------0 new points------------------------


0it [00:00, ?it/s]


[[1 3]]
-----------------------3------------------------
-----------------------0 new points------------------------


0it [00:00, ?it/s]

[[2 1]]
-----------------------4------------------------
-----------------------6 new points------------------------


Running on Glados
Governor set: Done
Frequency set: Done
energy_uj: Stdout: 6264402768

Running NONE with 3 threads

energy_uj: Stdout: 6264899386
NONE
    Stdout
        Running NONE with 3 threads
        OMP_NUM_THREADS=3
        OMP_PROC_BIND=CLOSE
        OMP_PLACES=CORES
        "Running None"
Running on Glados
Governor set: Done
Frequency set: Done
energy_uj: Stdout: 6275147040

Running NONE with 14 threads

energy_uj: Stdout: 6275661738
NONE
    Stdout
        Running NONE with 14 threads
        OMP_NUM_THREADS=14
        OMP_PROC_BIND=CLOSE
        OMP_PLACES=CORES
        "Running None"
Running on Glados
Governor set: Done
Frequency set: Done
energy_uj: Stdout: 6286068320

Running NONE with 12 threads

energy_uj: Stdout: 6286692204
NONE
    Stdout
        Running NONE with 12 threads
        OMP_NUM_THREADS=12
        OMP_PROC_BIND=CLOSE
        OMP_PLACES=CORES
        "Running None"
Running on Glados
Governor set: Done
Frequency set: Done
energy_uj: Stdout: 6297315846

Run

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00, 1618.69it/s]


[[2 2]]
-----------------------5------------------------
-----------------------0 new points------------------------


0it [00:00, ?it/s]


[[2 3]]
-----------------------6------------------------
-----------------------0 new points------------------------


0it [00:00, ?it/s]

[[3 1]]
-----------------------7------------------------
-----------------------6 new points------------------------


Running on Glados
Governor set: Done
Frequency set: Done
energy_uj: Stdout: 6421179908

Running NONE with 7 threads

energy_uj: Stdout: 6421701503
NONE
    Stdout
        Running NONE with 7 threads
        OMP_NUM_THREADS=7
        OMP_PROC_BIND=CLOSE
        OMP_PLACES=CORES
        "Running None"
Running on Glados
Governor set: Done
Frequency set: Done
energy_uj: Stdout: 6432282911

Running NONE with 10 threads

energy_uj: Stdout: 6432787905
NONE
    Stdout
        Running NONE with 10 threads
        OMP_NUM_THREADS=10
        OMP_PROC_BIND=CLOSE
        OMP_PLACES=CORES
        "Running None"
Running on Glados
Governor set: Done
Frequency set: Done
energy_uj: Stdout: 6443152985

Running NONE with 3 threads

energy_uj: Stdout: 6444106930
NONE
    Stdout
        Running NONE with 3 threads
        OMP_NUM_THREADS=3
        OMP_PROC_BIND=CLOSE
        OMP_PLACES=CORES
        "Running None"
Running on Glados
Governor set: Done
Frequency set: Done
energy_uj: Stdout: 6463176134

Runnin

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00, 1709.29it/s]


[[4 1]]
-----------------------8------------------------
-----------------------2 new points------------------------
Running on Glados
Governor set: Done
Frequency set: Done
energy_uj: Stdout: 6551289253

Running NONE with 15 threads

energy_uj: Stdout: 6551819515
NONE
    Stdout
        Running NONE with 15 threads
        OMP_NUM_THREADS=15
        OMP_PROC_BIND=CLOSE
        OMP_PLACES=CORES
        "Running None"
Running on Glados
Governor set: Done
Frequency set: Done
energy_uj: Stdout: 6562294574

Running NONE with 2 threads

energy_uj: Stdout: 6562799782
NONE
    Stdout
        Running NONE with 2 threads
        OMP_NUM_THREADS=2
        OMP_PROC_BIND=CLOSE
        OMP_PLACES=CORES
        "Running None"


100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 682.39it/s]


[[3 2]]
-----------------------9------------------------
-----------------------4 new points------------------------
Running on Glados
Governor set: Done
Frequency set: Done
energy_uj: Stdout: 6613729872

Running NONE with 7 threads

energy_uj: Stdout: 6614331190
NONE
    Stdout
        Running NONE with 7 threads
        OMP_NUM_THREADS=7
        OMP_PROC_BIND=CLOSE
        OMP_PLACES=CORES
        "Running None"
Running on Glados
Governor set: Done
Frequency set: Done
energy_uj: Stdout: 6624937865

Running NONE with 10 threads

energy_uj: Stdout: 6625538649
NONE
    Stdout
        Running NONE with 10 threads
        OMP_NUM_THREADS=10
        OMP_PROC_BIND=CLOSE
        OMP_PLACES=CORES
        "Running None"
Running on Glados
Governor set: Done
Frequency set: Done
energy_uj: Stdout: 6636996094

Running NONE with 7 threads

energy_uj: Stdout: 6637806981
NONE
    Stdout
        Running NONE with 7 threads
        OMP_NUM_THREADS=7
        OMP_PROC_BIND=CLOSE
        OMP_PLACES=CORES


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 1424.70it/s]


[[5 1]]
-----------------------10------------------------
-----------------------0 new points------------------------


0it [00:00, ?it/s]


[[4 2]]
-----------------------11------------------------
-----------------------4 new points------------------------
Running on Glados
Governor set: Done
Frequency set: Done
energy_uj: Stdout: 6912740395

Running NONE with 15 threads

energy_uj: Stdout: 6913381688
NONE
    Stdout
        Running NONE with 15 threads
        OMP_NUM_THREADS=15
        OMP_PROC_BIND=CLOSE
        OMP_PLACES=CORES
        "Running None"
Running on Glados
Governor set: Done
Frequency set: Done
energy_uj: Stdout: 6924252403

Running NONE with 2 threads

energy_uj: Stdout: 6924859092
NONE
    Stdout
        Running NONE with 2 threads
        OMP_NUM_THREADS=2
        OMP_PROC_BIND=CLOSE
        OMP_PLACES=CORES
        "Running None"
Running on Glados
Governor set: Done
Frequency set: Done
energy_uj: Stdout: 6935664212

Running NONE with 15 threads

energy_uj: Stdout: 6936496628
NONE
    Stdout
        Running NONE with 15 threads
        OMP_NUM_THREADS=15
        OMP_PROC_BIND=CLOSE
        OMP_PLACES=CO

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 1374.39it/s]


[[5 2]]
-----------------------12------------------------
-----------------------0 new points------------------------


0it [00:00, ?it/s]


[[6 1]]
-----------------------13------------------------
-----------------------5 new points------------------------
Running on Glados
Governor set: Done
Frequency set: Done
energy_uj: Stdout: 7203930887

Running NONE with 11 threads

energy_uj: Stdout: 7204461072
NONE
    Stdout
        Running NONE with 11 threads
        OMP_NUM_THREADS=11
        OMP_PROC_BIND=CLOSE
        OMP_PLACES=CORES
        "Running None"
Running on Glados
Governor set: Done
Frequency set: Done
energy_uj: Stdout: 7214869271

Running NONE with 13 threads

energy_uj: Stdout: 7215414668
NONE
    Stdout
        Running NONE with 13 threads
        OMP_NUM_THREADS=13
        OMP_PROC_BIND=CLOSE
        OMP_PLACES=CORES
        "Running None"
Running on Glados
Governor set: Done
Frequency set: Done
energy_uj: Stdout: 7225807655

Running NONE with 6 threads

energy_uj: Stdout: 7226326305
NONE
    Stdout
        Running NONE with 6 threads
        OMP_NUM_THREADS=6
        OMP_PROC_BIND=CLOSE
        OMP_PLACES=CO

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 987.08it/s]


[[7 1]]
-----------------------14------------------------
-----------------------0 new points------------------------


0it [00:00, ?it/s]


[[6 2]]
-----------------------15------------------------
-----------------------10 new points------------------------
Running on Glados
Governor set: Done
Frequency set: Done
energy_uj: Stdout: 7487643311

Running NONE with 6 threads

energy_uj: Stdout: 7488498263
NONE
    Stdout
        Running NONE with 6 threads
        OMP_NUM_THREADS=6
        OMP_PROC_BIND=CLOSE
        OMP_PLACES=CORES
        "Running None"
Running on Glados
Governor set: Done
Frequency set: Done
energy_uj: Stdout: 7507223933

Running NONE with 4 threads

energy_uj: Stdout: 7507850289
NONE
    Stdout
        Running NONE with 4 threads
        OMP_NUM_THREADS=4
        OMP_PROC_BIND=CLOSE
        OMP_PLACES=CORES
        "Running None"
Running on Glados
Governor set: Done
Frequency set: Done
energy_uj: Stdout: 7518500541

Running NONE with 9 threads

energy_uj: Stdout: 7519078636
NONE
    Stdout
        Running NONE with 9 threads
        OMP_NUM_THREADS=9
        OMP_PROC_BIND=CLOSE
        OMP_PLACES=CORES
 

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 1983.78it/s]


[[7 2]]
-----------------------16------------------------
-----------------------0 new points------------------------


0it [00:00, ?it/s]


[[3 3]]
-----------------------17------------------------
-----------------------0 new points------------------------


0it [00:00, ?it/s]


[[4 3]]
-----------------------18------------------------
-----------------------0 new points------------------------


0it [00:00, ?it/s]


[[5 3]]
-----------------------19------------------------
-----------------------0 new points------------------------


0it [00:00, ?it/s]


[[6 3]]
-----------------------20------------------------
-----------------------0 new points------------------------


0it [00:00, ?it/s]


[[7 3]]


ValueError: zero-size array to reduction operation maximum which has no identity

In [ ]:
len(analysis.l_norm)

21

In [ ]:
campaign.apply_analysis(analysis)
data_frame = campaign.get_collation_result()

In [ ]:
RESULTS_DIR = "run_results/"
persist.save(analysis, sampler, data_frame, vary, [QOI], RESULTS_DIR)